fail_fast: true
exclude: "(^vendor/|\\.patch$)"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: mixed-line-ending
        args: ["--fix=lf"]
        exclude: "\\.net$"
      - id: end-of-file-fixer
        exclude: "\\.out$"
      - id: trailing-whitespace
        exclude: "\\.out$"
      - id: check-merge-conflict
      - id: fix-byte-order-marker

