name: Codecov.io

on: [push, pull_request]

env:
  CMAKE_COLOR_DIAGNOSTICS: ON
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt-get install lcov libglpk-dev libarpack2-dev

    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Create build environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -G"Ninja" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DIGRAPH_ENABLE_TLS=ON -DIGRAPH_ENABLE_CODE_COVERAGE=ON -DFLEX_KEEP_LINE_NUMBERS=ON

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --parallel

    # No need to run coverage target, check is sufficient.
    # https://github.com/igraph/igraph/issues/2712#issuecomment-2567612369
    - name: Coverage
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --target coverage --parallel

    - name: Codecov.io
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
